model:
  name: ""
  params:
    dist_measure: "mix"
    lr: 0.05
    batch_size: 16
    wd: 0
    ls: 1
    l: 0.01
    beta: 0.4
    gamma: 0.5
dataset: "AtrialFibrillation"
algo: "fedcsl-onehot-splitteacher"
federated:
  numClient: 3
  numRound: 200
  numEpoch: 3
  dirichlet_alpha: 1
  use_client_selection: False
  client_selection_ratio: 0.6
  checkpoint_every: 30
  auto_resume: True

ablation:
  UseJointKD: True
  UseJointCL: True
  UseScaleKD: True
  UseScaleCL: True
  UseProdictor: False
  UseMTLHomo: False
  UseACF: True
  UseDistribution: False

logPath: "./result/"
description: "fedcsl-onehot-splitteacher"
